spring.config.import=configserver:http://localhost:8888
spring.application.name=SEARCH-SERVICE
spring.profiles.active=dev
eureka.instance.appname=SEARCH-SERVICE
eureka.instance.instance-id=SEARCH-SERVICE:${random.value}
spring.cloud.config.fail-fast=true
server.port=8086
