spring.config.import=configserver:http://localhost:8888
spring.application.name=USER-SERVICE
spring.profiles.active=dev
eureka.instance.appname=USER-SERVICE
eureka.instance.instance-id=USER-SERVICE:${random.value}
spring.cloud.config.fail-fast=true
server.port=8084
# JWT Configuration
jwt.expiration=3600000

#jwt.secret=${JWT}
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
