spring.application.name=CONFIG-SERVER
server.port=8888
eureka.instance.appname=CONFIG-SERVER
eureka.instance.instance-id=CONFIG-SERVER:${random.value}

# spring.cloud.config.server.git.uri=https://github.com/lakshmigavirni/CarRentalConfigRepo.git
# spring.cloud.config.server.git.default-label=main

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///c:/Users/chinn/Desktop/car%20rental%20system/RentEasy/config-server/CarRentalConfigRepo/

